import dagre from "dagre";

// Conversion between the Workflow backend format and React Flow nodes/edges.
// === UI Metadata Pocket ===
// The backend stores an opaque dictionary for the frontend in `Node.ui_metadata`:
// coordinates (`position: {x, y}`), sticker sizes, etc. The engine does
// NOT look into this field; it is a simple round-trip contract between the UI and JSON.
// === Auto-alignment (Dagre) ===
// Previously, coordinates were lost upon saving, and the UI created a primitive
// layered-layout `x = layer*280, y = slot*130`, which overlapped nodes in
// even slightly non-trivial graphs (especially for scenarios
// generated from Python code via `Workflow(...)` without positions). Now:
//   • on load, if AT LEAST ONE node lacks `ui_metadata.position`,
//     we run the entire graph through Dagre (rankdir LR) — and get
//     a guaranteed non-overlapping layout without manual tuning;
//   • on save, we write `ui_metadata.position = {x, y}` from the current
//     `node.position` in React Flow — positions persist across sessions.
const FALLBACK_NODE_WIDTH = 220;
const FALLBACK_NODE_HEIGHT = 90;
const NOTE_DEFAULT_WIDTH = 240;
const NOTE_DEFAULT_HEIGHT = 160;

// Dagre layout. Called only when positions are missing (or partially
// missing)—not on every load. `rankdir: LR`—left to right, which
// aligns with our mental model “trigger → ... → output”. Generous
// `nodesep`/`ranksep` values provide enough space for port handles.
function computeLayout(nodes, edges) {
  const g = new dagre.graphlib.Graph();
  g.setGraph({ rankdir: "LR", nodesep: 30, ranksep: 80 });
  g.setDefaultEdgeLabel(() => ({}));

  for (const n of nodes) {
    // For note stickers, we use their actual size (from ui_metadata
    // or the config fallback) — otherwise, a large sticker will overlap with neighboring stickers.
    const isNote = n.type === "note";
    const ui = n.ui_metadata || {};
    const cfg = n.config || {};
    const width = isNote
      ? (ui.width ?? cfg.width ?? NOTE_DEFAULT_WIDTH)
      : FALLBACK_NODE_WIDTH;
    const height = isNote
      ? (ui.height ?? cfg.height ?? NOTE_DEFAULT_HEIGHT)
      : FALLBACK_NODE_HEIGHT;
    g.setNode(n.id, { width, height });
  }

  for (const e of edges) {
    const src = e.from ?? e.from_node;
    const tgt = e.to ?? e.to_node;
    if (!src || !tgt) continue;
    if (!g.hasNode(src) || !g.hasNode(tgt)) continue;
    g.setEdge(src, tgt);
  }

  dagre.layout(g);

  // Dagre returns the coordinates of the node's CENTER; React Flow positions the node
  // at the top-left corner — let's convert them.
  const positions = {};
  for (const n of nodes) {
    const node = g.node(n.id);
    if (!node) {
      positions[n.id] = { x: 40, y: 40 };
      continue;
    }
    positions[n.id] = {
      x: Math.round(node.x - node.width / 2),
      y: Math.round(node.y - node.height / 2),
    };
  }
  return positions;
}

// Backend Workflow → React Flow state.
export function workflowToFlow(workflow) {
  const nodes = workflow.nodes || [];
  const edges = workflow.edges || [];

  // If at least one node is missing `ui_metadata.position`, we load
  // the entire graph into dagre. This covers both cases:
  //  (a) a scene generated by Python code without visual coordinates;
  //  (b) old saved scenarios that have not yet been processed by `save-with-positions`.
  const needsLayout = nodes.some((n) => {
    const pos = n.ui_metadata?.position;
    return !pos || typeof pos.x !== "number" || typeof pos.y !== "number";
  });
  const dagrePositions = needsLayout ? computeLayout(nodes, edges) : {};

  const flowNodes = nodes.map((n) => {
    const cfg = structuredClone(n.config ?? {});
    const uiMeta = structuredClone(n.ui_metadata ?? {});
    const reactFlowType = n.type === "note" ? "note" : "nexus";

    const explicitPos = uiMeta.position;
    const position =
      explicitPos && typeof explicitPos.x === "number" && typeof explicitPos.y === "number"
        ? { x: explicitPos.x, y: explicitPos.y }
        : (dagrePositions[n.id] || { x: 40, y: 40 });

    const node = {
      id: n.id,
      type: reactFlowType,
      position,
      data: {
        type: n.type,
        config: cfg,
        ui_metadata: uiMeta,
        // System attribute — how the engine interprets input edges (AND/OR).
        trigger_rule: n.trigger_rule || "all_success",
      },
    };

    if (n.type === "note") {
      // Migration: first ui_metadata (new standard), then config (old
      // workflows that haven't yet gone through the save cycle following the ui_metadata feature).
      const w = uiMeta.width ?? cfg.width ?? NOTE_DEFAULT_WIDTH;
      const h = uiMeta.height ?? cfg.height ?? NOTE_DEFAULT_HEIGHT;
      // React Flow reads `style.width/height` for the resize bounding box—so that
      // NodeResizer starts with the correct size immediately after loading.
      node.style = { width: w, height: h };
      // Mirror in data.ui_metadata so that NoteNodes/handlers always read
      // from a single source (new convention—width/height are stored here).
      node.data.ui_metadata = { ...node.data.ui_metadata, width: w, height: h };
    }
    return node;
  });

  const flowEdges = edges.map((e, i) => {
    const src = e.from ?? e.from_node;
    const tgt = e.to ?? e.to_node;
    const sh = e.source_handle ?? null;
    const th = e.target_handle ?? null;
    return {
      id: `e_${src}_${tgt}_${i}`,
      source: src,
      target: tgt,
      ...(sh ? { sourceHandle: sh } : {}),
      ...(th ? { targetHandle: th } : {}),
      data: { is_readonly: !!e.is_readonly },
    };
  });

  return {
    name: workflow.name || "",
    nodes: flowNodes,
    edges: flowEdges,
    isReadonly: !!workflow.is_readonly,
  };
}

// React Flow state → backend Workflow JSON.
export function flowToWorkflow(name, flowNodes, flowEdges, options = {}) {
  return {
    name: name || "untitled",
    is_readonly: !!options.isReadonly,
    nodes: flowNodes.map((n) => {
      // We build ui_metadata “from scratch” based on the current state of React Flow,
      // keeping only what we actually need for the round-trip:
      //  • position — always from `n.position` (React Flow's live state);
      //  • width/height — only for note stickers (from n.style or data).
      const uiMeta = {
        ...(n.data?.ui_metadata || {}),
        position: {
          x: Math.round(n.position?.x ?? 0),
          y: Math.round(n.position?.y ?? 0),
        },
      };

      if (n.data?.type === "note") {
        // Let's resolve the size based on priority: React Flow style → data.ui_metadata
        // → default. The style takes precedence because NodeResizer updates it
        // on the fly, even if the patch hasn't reached data.ui_metadata yet.
        let w = n.data?.ui_metadata?.width ?? n.measured?.width ?? n.style?.width ?? NOTE_DEFAULT_WIDTH;
        let h = n.data?.ui_metadata?.height ?? n.measured?.height ?? n.style?.height ?? NOTE_DEFAULT_HEIGHT;

        // Safely remove “px” in case a line ended up there
        w = typeof w === 'string' ? parseFloat(w.replace('px', '')) : w;
        h = typeof h === 'string' ? parseFloat(h.replace('px', '')) : h;

        uiMeta.width = Math.round(w) || NOTE_DEFAULT_WIDTH;
        uiMeta.height = Math.round(h) || NOTE_DEFAULT_HEIGHT;
      }

      return {
        id: n.id,
        type: n.data.type,
        config: n.data.config,
        // We only pass the trigger rule if it is not the default—so that the JSON
        // remains minimal for standard workflows.
        ...(n.data.trigger_rule && n.data.trigger_rule !== "all_success"
          ? { trigger_rule: n.data.trigger_rule }
          : {}),
        ui_metadata: uiMeta,
      };
    }),
    edges: flowEdges.map((e) => ({
      from: e.source,
      to: e.target,
      ...(e.sourceHandle ? { source_handle: e.sourceHandle } : {}),
      ...(e.targetHandle ? { target_handle: e.targetHandle } : {}),
      ...(e.data?.is_readonly ? { is_readonly: true } : {}),
    })),
  };
}
